import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import "../styles/globals.css";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/Footer";
import Provider from "./providers/SessionProvider";
import Modal from "@/components/modals/Modal";
import RegisterModal from "@/components/modals/RegisterModal";
import ToasterProvider from "./providers/ToasterProvider";

const raleway = Raleway({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "StudyNook",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={raleway.className}>
        <Provider>
          <ToasterProvider />
          <RegisterModal />
          <Navbar />
          {children}
          <Footer />
        </Provider>
      </body>
    </html>
  );
}
